apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: hello-gardener
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: GardenerShootControlPlane
    name: hello-gardener
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: GardenerShootControlPlane
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-gardener
    app.kubernetes.io/managed-by: kustomize
  name: hello-gardener
spec:
  project: local
  shootSpec:
    cloudProfile:
      kind: CloudProfile
      name: local
    secretBindingName: local # dummy, doesn't contain any credentials
    region: local
    networking:
      type: calico
      nodes: 10.10.0.0/16
    provider:
      type: local
      workers:
        - name: local
          machine:
            type: local
          cri:
            name: containerd
          minimum: 1
          maximum: 2
          maxSurge: 1
          maxUnavailable: 0
    kubernetes:
      kubelet:
        seccompDefault: true
        serializeImagePulls: false
        registryPullQPS: 10
        registryBurst: 20
        protectKernelDefaults: true
        streamingConnectionIdleTimeout: 5m
