apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: hello-gardener
spec:
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
    kind: GardenerShootCluster
    name: hello-gardener
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: GardenerShootControlPlane
    name: hello-gardener
    namespace: default
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: GardenerShootControlPlane
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-gardener
    app.kubernetes.io/managed-by: kustomize
  name: hello-gardener
spec:
  # Defaulted to this objects namespace if not provided.
  projectNamespace: garden-local

  cloudProfile:
    kind: CloudProfile
    name: local
  provider:
    type: local
  kubernetes:
    version: "1.32"
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: GardenerShootCluster
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-gardener
    app.kubernetes.io/managed-by: kustomize
  name: hello-gardener
spec:
  region: local
