apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: hello-gardener
spec:
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
    kind: GardenerShootControlPlane
    name: hello-gardener
---
apiVersion: controlplane.cluster.x-k8s.io/v1alpha1
kind: GardenerShootControlPlane
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-gardener
    app.kubernetes.io/managed-by: kustomize
  name: hello-gardener
spec:
  # Defaulted to this objects namespace if not provided.
  projectNamespace: garden-local
  shootSpec:
      cloudProfile:
        kind: CloudProfile
        name: local
      region: local
      provider:
        type: local
      kubernetes:
        version: "1.32"

