apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: GardenerShootCluster
metadata:
  labels:
    app.kubernetes.io/name: cluster-api-provider-gardener
    app.kubernetes.io/managed-by: kustomize
  name: gardenershootcluster-sample
spec:
  # TODO(user): Add fields here
