name: E2E Tests

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
  pull_request:
    branches:
      - main

jobs:
  test-e2e:
    name: Run on Ubuntu
    runs-on: ubuntu-latest
    env:
      JOB_NAME: cluster-api-provider-gardener
      BUILD_ID: dummy
    steps:
      - name: Clone the code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Install the latest version of kind
        run: |
          curl -Lo ./kind https://kind.sigs.k8s.io/dl/latest/kind-linux-amd64
          chmod +x ./kind
          sudo mv ./kind /usr/local/bin/kind

      - name: Verify kind installation
        run: kind version

      - name: Add hosts to /etc/hosts
        run: |
          sudo echo "127.0.0.1 garden.local.gardener.cloud" | sudo tee -a /etc/hosts

      - name: Create Gardener kind cluster
        run: |
          go mod tidy
          make kind-gardener-up
          make clusterctl-init

      - name: Running Test e2e
        run: |
          make test-e2e
